### ISSUE TITLE
Fix the position of the stop button

### ISSUE THREAD

**Issue by seonwoo960000** [seonwoo960000/ai-sidebar#15]
**Describe the feature you want to request**
When a received message is being streamed, a "Stop" button can be seen by the users. But because the stop button is positioned in the same element where the received messages are shown, the stop button moves downward together like below. 
![main](https://github.com/seonwoo960000/ai-sidebar/assets/69591622/8756665c-e421-404c-ab1b-559d3909ae5c)

It'll be a bad experience for the users because the stop button seems to be moving. Let's make the button fixed even though the messages are being received(in a stream fashion) 

**Describe how you want to implement the feature**
Maybe using css `grid` or whatever better implementation would be fine. But the rule "stop button should be shown when the message is being streamed" should not change.

**Comment by aishwarya-mali** [comment]
@seonwoo960000 I'd like to work on this issue.

**Comment by seonwoo960000** [comment]
Sure @aishwarya-mali! It's all yours, thanks 👍

**Comment by aishwarya-mali** [comment]
@seonwoo960000 I have followed instructions as per README but I'm getting **API key is invalid** error.

**Comment by seonwoo960000** [comment]
@aishwarya-mali Oh, have you set your "personal" OpenAI api key into the settings? If yes, change a function in `Chat.vue` and shoe me the error printed out in the console. 

as-is
```
function onApiKeyError(err: string) {
  eventBus.emit(EventName.OPEN_SETTINGS, { "err": err });
  eventBus.emit(EventName.OPEN_SNACKBAR, { text: "API key is invalid", color: "error" });
}
```

to-be
```
function onApiKeyError(err: string) {
  console.log(err)
  eventBus.emit(EventName.OPEN_SETTINGS, { "err": err });
  eventBus.emit(EventName.OPEN_SNACKBAR, { text: "API key is invalid", color: "error" });
}
```

**Comment by aishwarya-mali** [comment]
Below is the error
<img width="320" alt="image" src="https://github.com/seonwoo960000/ai-sidebar/assets/43086476/de899bd7-6248-420c-afc9-9378104ed729">

**Comment by seonwoo960000** [comment]
I think it's because you exceeded the API usage(I guess you are using free tier?). If you want to use the openai API, you have to enter billing information to upgrade to a paid plan. 

referenece: https://help.openai.com/en/articles/4936830-what-happens-after-i-use-my-free-tokens-or-the-3-months-is-up-in-the-free-trial

**Comment by seonwoo960000** [comment]
I think we should handle errors as @aishwarya-mali showed with different error messages. It will be handed by the following issue: https://github.com/seonwoo960000/ai-sidebar/issues/9

**Comment by aishwarya-mali** [comment]
> I think it's because you exceeded the API usage(I guess you are using free tier?). If you want to use the openai API, you have to enter billing information to upgrade to a paid plan.
> 
> referenece: https://help.openai.com/en/articles/4936830-what-happens-after-i-use-my-free-tokens-or-the-3-months-is-up-in-the-free-trial

I use free tier. but have created API keys just today. Is it necessary to have paid plan to use the extension and resolve the issue?

**Comment by seonwoo960000** [comment]
Even if you made the API keys today, the quota may be calculated based on the overall usage of the openAI service usage(That's why you got blocked by the 429 error). 

> Is it necessary to have paid plan to use the extension
If quota is not exceeded, you don't need the paid plan. But if quota has exceeded, then you need to have a paid plan 😢

**Comment by seonwoo960000** [comment]
@aishwarya-mali, I'll add a feature that we can mock openAi response so that we don't need openAi api keys in development mode 😄

**Comment by aishwarya-mali** [comment]
@seonwoo960000 Thanks! That will be helpful.

**Comment by seonwoo960000** [comment]
@aishwarya-mali , it has been handled in below PR: 
https://github.com/seonwoo960000/ai-sidebar/pull/46
